services:
  # # Temporary setup container to build the folder structure
  init-folders:
    image: alpine:latest
    container_name: bricktracker-init
    volumes:
      - $BRICKTRACKER_FOLDER:/app/data
    command: sh -c "mkdir -p /app/data/sets /app/data/parts /app/data/minifigs /app/data/instructions && chown -R $PUID:$PGID /app/data"
    restart: "no"
         
  bricktracker:
    image: gitea.baerentsen.space/frederikbaerentsen/bricktracker:latest
    container_name: bricktracker
    ports:
      - "3333:3333"
    environment:
      - BK_REBRICKABLE_API_KEY=$BK_REBRICKABLE_API_KEY
    volumes:
      - $BRICKTRACKER_FOLDER:/app/data:rw  # v1.3+ consolidates everything into /app/data
    depends_on:
      init-folders:
        condition: service_completed_successfully
    restart: unless-stopped
               
  legoscanner:
    image: ghcr.io/bamnodct/legodisassemblytracker:main
    container_name: legoscanner
    volumes:
      - $BRICKTRACKER_FOLDER:/workspaces/legoscanner/bricktracker/:rw
    environment:
      - CAMERA_API=$CAMERA_API
    depends_on:
      init-folders:
        condition: service_completed_successfully
    ports:
      - "8501:8501"